export const SequenceDefault = [
    {   step:0,
        active:false,
        octave:null,
        note:null,
    },
    {   step:1,
        active:false,
        octave:null,
        note:null,
    },
    {   step:2,
        active:false,
        octave:null,
        note:null,
    },
    {   step:3,
        active:false,
        octave:null,
        note:null,
    },
    {   step:4,
        active:false,
        octave:null,
        note:null,
    },
    {   step:5,
        active:false,
        octave:null,
        note:null,
    },
    {   step:6,
        active:false,
        octave:null,
        note:null,
    },
    {   step:7,
        active:false,
        octave:null,
        note:null,
    },
    {   step:8,
        active:false,
        octave:null,
        note:null,
    },
    {   step:9,
        active:false,
        octive:null,
        note:null,
    },
    {   step:10,
        active:false,
        octave:null,
        note:null,
    },
    {   step:11,
        active:false,
        octave:null,
        note:null,
    },
    {   step:12,
        active:false,
        octave:null,
        note:null,
    },
    {   step:13,
        active:false,
        octave:null,
        note:null,
    },
    {   step:14,
        active:false,
        octave:null,
        note:null,
    },
    {   step:15,
        active:false,
        octave:null,
        note:null,
    },
]

